### ISSUE TITLE
User-can-view-all-pokemon-1

### ISSUE THREAD

**Issue by DavidKyong** [DavidKyong/ajax-project#1]
## 📐 Plan

> ##### A description of how the application will work from the perspective of the user.

Create a page to view all the 1st generation pokemon in order with bulbasaur at number 1 all the way through to mew at 151.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-06-13 at 10 33 40 PM](https://github.com/DavidKyong/ajax-project/assets/77517004/ed69814b-5439-436e-aee5-76baf3ba1654)

![Screenshot 2023-06-13 at 10 33 51 PM](https://github.com/DavidKyong/ajax-project/assets/77517004/6f917add-8d36-45c3-a185-25dca585d60a)

![Screenshot 2023-06-13 at 10 34 02 PM](https://github.com/DavidKyong/ajax-project/assets/77517004/4ff0de0c-77b8-46d7-a42c-02ffe3627e27)

![Screenshot 2023-06-13 at 10 34 11 PM](https://github.com/DavidKyong/ajax-project/assets/77517004/a1a48717-855a-476f-8f9e-0576ebf39540)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the basic html for the figma.
>- [x] Create the navbar with the title and headers.
>- [x] Add the title of the page and the search bar.
>- [x] Add the image placeholders in place of the empty place for the pokemon image and add the pokemon name and # underneath as a placeholder for now.
- [x] Add the necessary CSS styling.
- [x] After the page looks like the figma, make sure that it looks the same as the figma for both mobile and desktop screens.
- [x] In main.js, make a GET request to get each pokemon name as a response back.
- [x] Render each response to fill in the spots of the placeholders.
- [x] If the image and name show up over the placeholders, remove the placeholders in html.
- [x] Refresh the page and make sure the pokemon come out with the right image and name.
- [x] Remove unnecessary html, css styling, and javascript that does not change the page.
