### ISSUE TITLE
User-can-view-pokemon-by-types-2

### ISSUE THREAD

**Issue by DavidKyong** [DavidKyong/ajax-project#2]
## ⚙️ Feature

> ##### User will be able to see all 151 pokemon. Then they will be able to view each type and see which pokemons have that type.

## 📐 Functionality

> ##### When the user clicks on types, they will be able to view all the pokemon separated by their types. Some pokemon will have more than one type.

## 🖼️ Wireframes

![Screenshot 2023-06-14 at 9 43 38 PM](https://github.com/DavidKyong/ajax-project/assets/77517004/90923ec5-018c-4048-be29-ac8e45d91a94)
![Screenshot 2023-06-14 at 9 43 56 PM](https://github.com/DavidKyong/ajax-project/assets/77517004/c8b7653c-4be3-47c7-bbce-587bc74d70e4)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create more arrays to hold all the pokemon pictures in order by each type.
- [x] Dom query each row made for each type of pokemon.
- [x] GET request each type of pokemon from the url separately. (That way it is not requesting everything all at once.)
- [x] From the response back, render the names and the images into each type. Look over everything and make sure the names, images, and the types match each pokemon.
- [x] Remove the placeholders in the html.
- [x] Dom query the types title and the main title in the navbar. Add an addeventlistener listening for a 'click' on the types title and the main title. Clicking on the types should "hide" the all the pokemon on the homepage. Clicking on the main title should show all the pokemon on the homepage.
- [x] Check both mobile and desktop to see if they match the figma.
- [x] Make necessary changes to the css, html, and javascript to make it look and function as stated.
