### ISSUE TITLE
User-can-save-pokemon-3

### ISSUE THREAD

**Issue by DavidKyong** [DavidKyong/ajax-project#3]
## ⚙️ Feature

> ##### User will be able to view a clicked pokemon and save it.

## 📐 Functionality

> ##### User will click on a specific pokemon and will be taken to a page with just that pokemon and will have the option to add it into a saved file.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-06-15 at 7 58 34 PM](https://github.com/DavidKyong/ajax-project/assets/77517004/e3019332-81ac-449a-8659-6332b46266c9)
![Screenshot 2023-06-15 at 7 58 51 PM](https://github.com/DavidKyong/ajax-project/assets/77517004/a952feec-bfea-4d97-a282-343bd06dd1b5)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the html layout to look like the figma.
- [x] Using CSS, space out the image and wordings so it matches both mobile and desktop screen.
- [x] Dom query all class name that holds the image and the name (.row.pokemon-pic).
- [x] Add an event listener to the row-content to listen for click.
  - [x] "Hides" all of the other pages and just shows only the clicked on pokemon.
  - [x] Have to make sure that the event.target matches that of the clicked pokemon. Get the attribute of the clicked on image and query select it into a new variable. Create new elements and render the name and image into a new page.
  - [x]  Since we only want to show the clicked on pokemon, we check the existing pokemon on the page with a new clicked pokemon. If there is already a pokemon on the new page, we remove the elements with the name and image. Only one pokemon should we showing at a time.
  - [x] Create a local storage to store all of the saved pokemon data.
 - [x] Add an event listener to the plus icon to listen for the click.
  - [x] After the click, the pokemon data should be saved into the local storage.
  - [x] Console log to make sure it is working correctly and getting only the clicked on pokemon.
 - [x] Try it out on mutiple pokemons.
 - [x] Remove unnecessary CSS, html, and javascript.
