### ISSUE TITLE
User-can-view-saved-pokemon

### ISSUE THREAD

**Issue by DavidKyong** [DavidKyong/ajax-project#4]
> ##### User will be able to view the saved pokemon in a separate view page.

## 📐 Functionality

> ##### After the user clicks on the plus icon, they will be taken to the saved page. Also, if you click on the saved in the navbar, it will take the user to the saved page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="642" alt="Screenshot 2023-06-25 at 3 55 47 PM" src="https://github.com/DavidKyong/Pokedex-Types/assets/77517004/7bb0ce05-b2e0-44d8-ab23-fbf8d7898dc6">
<img width="275" alt="Screenshot 2023-06-25 at 3 56 03 PM" src="https://github.com/DavidKyong/Pokedex-Types/assets/77517004/60b24b91-ad21-4a80-b9a1-09d26fd97a85">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a click event to the saved menu in the navbar to hide everything except the saved page.
- [x] Uses the data in the local storage, render each of the pokemon name and the image newest to oldest data. The newest saved pokemon should be first on the list in the saved page.
- [x] Make sure that there are no repeats in the saved pokemon page by using conditional statements.
- [x] Try it out on multiple pokemons.
- [x] Fix up any css styling needed.
