### ISSUE TITLE
User-can-search-for-pokemon

### ISSUE THREAD

**Issue by DavidKyong** [DavidKyong/ajax-project#5]
## ⚙️ Feature

> ##### User will be able to search for a Pokemon by its name.

## 📐 Functionality

> ##### When typing in the search bar, any Pokemon that has the letters in the same order as it was typed in will show up.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-07-23 at 9 20 04 PM](https://github.com/DavidKyong/Pokedex-Types/assets/77517004/4d721b69-6ea8-478c-8400-1f3665255853)

![Screenshot 2023-07-23 at 9 20 17 PM](https://github.com/DavidKyong/Pokedex-Types/assets/77517004/01f127b9-df43-4077-aa17-af0a183b0670)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Dom query the search bar and add an event listener to it, listening for an input.
- [x] Within the event listener, dom query the class names that are included with the pokemon name.
  - [x] Make sure to change it to lower case, that way the user will be able to search the name and still get the results whether 
          it was capitalized or not.
- [x] Loop through each element and separate the column-one-fifth from the pokemon name.
  - [x] Using conditional statements, check to see if the pokemon name includes the typed input.
  - [x] If it doesn't, then it adds 'hidden' which hides the pokemon column.
  - [x] If it does exist, then it removed 'hidden' that way it can show the pokemon.
  - [x] Use true/false in another conditional statement to see if the class name has 'hidden' in it or not.
- [x] If nothing from the input matches that of the pokemon name from the class list, then it hides all of the pokemon column and shows "No matches found".
- [ ] Check the CSS, javascript, and html. Make sure everything is still working fine.
